import type { UnitDefinition, UnitType } from '../types';

export const UNIT_DEFINITIONS: Record<UnitType, UnitDefinition> = {
  Hastati: {
    type: 'Hastati',
    label: 'Hastati',
    baseHp: 50,
    baseAtk: 12,
    baseDef: 8,
    cost: 50,
    isRanged: false,
    speed: 0.8,
    range: 36,
    color: '#ef4444',
    description: 'Light infantry — cheap and plentiful.',
  },
  Legionary: {
    type: 'Legionary',
    label: 'Legionary',
    baseHp: 80,
    baseAtk: 15,
    baseDef: 12,
    cost: 100,
    isRanged: false,
    speed: 0.6,
    range: 36,
    color: '#dc2626',
    description: 'Heavy infantry — backbone of the legion.',
  },
  Archer: {
    type: 'Archer',
    label: 'Archer',
    baseHp: 40,
    baseAtk: 14,
    baseDef: 5,
    cost: 60,
    isRanged: true,
    speed: 0.5,
    range: 180,
    color: '#f97316',
    description: 'Ranged skirmisher — fires arrows from distance.',
  },
  Equites: {
    type: 'Equites',
    label: 'Equites',
    baseHp: 60,
    baseAtk: 18,
    baseDef: 10,
    cost: 120,
    isRanged: false,
    speed: 1.6,
    range: 40,
    color: '#eab308',
    description: 'Cavalry — fast flankers with high attack.',
  },
  Ballista: {
    type: 'Ballista',
    label: 'Ballista',
    baseHp: 30,
    baseAtk: 25,
    baseDef: 3,
    cost: 150,
    isRanged: true,
    speed: 0.2,
    range: 250,
    color: '#a855f7',
    description: 'Siege engine — devastating ranged power, fragile.',
  },
  Praetorian: {
    type: 'Praetorian',
    label: 'Praetorian Guard',
    baseHp: 100,
    baseAtk: 20,
    baseDef: 18,
    cost: 200,
    isRanged: false,
    speed: 0.7,
    range: 38,
    color: '#c9a84c',
    description: 'Elite guard — finest soldiers in Rome.',
  },
};

export const UNIT_ORDER: UnitType[] = [
  'Hastati',
  'Legionary',
  'Archer',
  'Equites',
  'Ballista',
  'Praetorian',
];
